Added CCB commands (add, rm, approve, block) and associated changes t…
daedaleanai/git-ticket pull request #37
Opened 2021-08-16 11:24 UTC by dawzee

…o store in ticket, show status, read ccb members from config and prevent ticket transition without approval

2021-09-01 12:09 UTC, aleb requested changes
some nitpicks

2021-09-02 16:12 UTC, dawzee commented on commands/ccb_rm.go
> +		Use:      "rm <user> [<id>]",
Hmm, should be optional as long as you have a ticket selected:
```
iw@iw:~/sandpit/git-ticket/one-id-and-bug(master)$ git ticket show --field ccb
Ian Whittington (Approved)
Martin Beeby (Added)
iw@iw:~/sandpit/git-ticket/one-id-and-bug(master)$ git ticket ccb rm Martin
Removing Martin Beeby from CCB group of ticket 6873dbb
iw@iw:~/sandpit/git-ticket/one-id-and-bug(master)$ git ticket show --field ccb
Ian Whittington (Approved)
iw@iw:~/sandpit/git-ticket/one-id-and-bug(master)$ git ticket ccb add Martin
Adding Martin Beeby to CCB group of ticket 6873dbb
```

with no ticket selected you get an error:
```
iw@iw:~/sandpit/git-ticket/one-id-and-bug(master)$ git ticket deselect
iw@iw:~/sandpit/git-ticket/one-id-and-bug(master)$ git ticket ccb rm Martin
Error: you must provide a ticket id or use the "select" command first
```

2021-09-02 16:28 UTC, dawzee commented on commands/ccb_rm.go
> +		return errors.New(userToRemoveIdentity.DisplayName() + " is not in the ticket CCB group")
good point, the ticket is already is already in the intended state so returning an error seems counter-intuitive. fixed here and in other commands.

2021-09-03 06:45 UTC, dawzee commented on bug/ccb.go
> +// configuration. Configurations must be of the form "map[string]interface{}" so is stored as {"<user id>":1}.
good idea. fixed.

2021-09-03 20:21 UTC, aleb commented on commands/ccb_rm.go
> +		Use:      "rm <user> [<id>]",
nice! :)

2021-09-03 20:21 UTC, aleb approved these changes
LGTM

2021-09-06 05:56 UTC, merged