extended ccb function to allow members to be assigned per status
daedaleanai/git-ticket pull request #39
Opened 2021-11-09 12:28 UTC by dawzee

through using the ccb function it became clear we needed more precise control, i.e. the ability to have multiple ccb's on a ticket. this PR modifies the ccb commands so that members must be added to a ticket with relation to a certain status, when it's approved it's only for the "next" status. typical workflow will be:

1) ticket created (in "proposed" state), ccb members added to "vetted" and "accepted" statuses
2) ccb members approve ticket, ticket moved to "vetted"
3) ticket goes through other statuses during the change process, ending up in "reviewed"
3) ccb members approve ticket, ticket moved to "accepted"
5) changes merged and ticket moved to "merged"

2021-11-17 15:11 UTC, aleb requested changes
The status of the review is finished, the state is lots of comments. :D

2021-11-17 15:11 UTC, aleb commented on bug/workflow.go
> +	nextStates, _ := w.NextStates(from)
Since `from` is a `Status`, `NextStates` should be renamed to `NextStatuses` to avoid confusion now that we use both "state" and "status"?

2021-11-17 15:11 UTC, aleb commented on bug/workflow.go
> +	return fmt.Errorf("invalid transition %s->%s, possible next states: %s", from, to, nextStates)
"possible next statuses"? https://www.merriam-webster.com/dictionary/status plural statuses

2021-11-17 15:11 UTC, aleb commented on commands/ccb_add.go
> +	fmt.Printf("Adding %s to %s CCB group of ticket %s\n", userToAddIdentity.DisplayName(), status, b.Id().Human())
"Promoting %s as warden of ticket %s CCB status %s" ?

2021-11-18 14:57 UTC, dawzee commented on commands/ccb_block.go
> +			return nil
yeah.... after a bit of consideration I think this is overly complicated with little benefit. I've simplified the approve/block command so that the user needs to say which status they want to approve/block. The ticket no longer needs to be in the preceeding status in order to approve/block.

2021-11-24 14:19 UTC, merged