Added refresh command to update the cache; sped up pull command
daedaleanai/git-ticket pull request #47
Opened 2022-12-16 07:40 UTC by dawzee

Added a refresh command that can be used server-side to update the cache (so it doesn't need to be rebuilt from scratch when changes are pushed or landed in other repos). At the same time sped up the Pull command massively by checking the commit history of a bug before bothering to load it.

2022-12-16 12:48 UTC, aleb requested changes

2022-12-16 12:48 UTC, aleb commented on bug/bug_actions.go
> +				continue
add a comment line to explain why we're continuing

2022-12-16 12:48 UTC, aleb commented on cache/repo_cache_common.go
> +	// updated to include the last edit time, then we could so something clever like with
*do

2022-12-16 12:48 UTC, aleb commented on cache/repo_cache_common.go
> +// RefreshResult holds the state of each if that was updated
"holds the state of a bug that is new or has been updated."

2022-12-20 19:03 UTC, dawzee commented on bug/bug_actions.go
> +				continue
comment added, including why 'err != nil' is ignored

2022-12-20 19:07 UTC, dawzee commented on identity/identity_actions.go
> +			if err == nil && hashes == nil {
added comment (as bug_actions) as to why non-nil err is not handled.

2022-12-20 19:19 UTC, dawzee commented on repository/git.go
> +func (repo *GitRepo) CommitsBetween(beforeRef, afterRef string) ([]Hash, error) {
changed to mainRef and excludeRef (feel free to suggest something better)

2022-12-21 07:31 UTC, dawzee commented on repository/git.go
> +		return nil, nil
good question. In the calling function I check for hash being nil to indicate that there are no commits. I could check for zero length slice instead but [this](https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices) suggests that nil slice is preferred.

2022-12-28 13:30 UTC, aleb approved these changes
LGTM

2022-12-29 17:53 UTC, merged